version: '3.3'

services:
#  rabbit-service:
#    build: RabbitMain
##    hostname: rabbitmq
#    container_name: rabbit-service

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbit

#  rabbitmq:
#    build: RabbitMq
#    hostname: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    container_name: rabbitmq
#  node-js:
#    build: NodeJsApp
#    ports:
#      - 8800:8800
#    depends_on:
#      - rabbit
#    container_name: node-js
#
#  postgres:
#    image: postgres
#    ports:
#      - 5433:5432
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=docker
#      - POSTGRES_DB=docker-db

  cat-service:
    build: CatService
    ports:
      - 8081:8081
    depends_on:
      - rabbit
    container_name: cat-service

  registry-service:
    build: RegistryService
    ports:
      - 8083:8083
    depends_on:
      - rabbit
      - cat-service
    container_name: registry-service

  zuul-service:
    build: ZuulService
    container_name: zuul-service
    ports:
      - 8080:8080
    depends_on:
      - cat-service
      - registry-service

  registartion:
    build: RegistrationService
    container_name: registration
    ports:
      - 8082:8082
    depends_on:
      - rabbit

  service-registry:
    build: ServiceRegistry
    container_name: eureka-server
    ports:
      - 9000:9000
    depends_on:
      - cat-service
      - registry-service
      - zuul-service