zuul:
  prefix: /api
  routes:
    user:
      path: /cat/**
      serviceId: CAT
#    country:
#      path: /country/**
#      serviceId: COUNTRY
    server:
      path: /server/**
      servcieId: SERVER

    reg:
      path: /reg/**
      serviceId: REG